name: Google Java Format

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  formatting:
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Robot Code
        run: ./gradlew build
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--replace"
